language: php
php:
  - 7.1
before_script:
  - composer install --no-interaction
before_install:
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS test;'
script:
  - composer test
after_script:
  - ./vendor/bin/coveralls
